var arrPro = [{
        id: 1,
        name: "Áo Thun Nam Cool Off Shirt Knock",
        price: 317374,
        urlPic: "./images/aothunnam/1.jpg",
        urlPic2: "./images/aothunnam/1_1.jpg",
        des: "Classic T-shirt - sets the standard for fabric and production quality, durability and wearer comfort.100% cotton, high quality fabric and top level finishing.",
        idLoai: 1,
        new: 0,
        hot: 1,
        star: 4,
        sale: 1,
        view: 1
    },
    {
        id: 2,
        name: "Size 8.5 - Jordan 1 Mid Metallic Red ",
        price: 3023255,
        urlPic: "./images/shoe/1.jpg",
        urlPic2: "./images/shoe/1_1.jpg",
        des: "We realize not every pair of sneakers from Nike is perfect, nor is the shoe box always perfect.In order to pass authentication, the buyer assumes all responsibility in the event there are factory flaws, defects, or imperfections when it comes to the shoes. The buyer also assumes all responsibility in the event there is damage to the shoe box, or box lid...",
        idLoai: 2,
        new: 1,
        hot: 1,
        star: 4.5,
        sale: 1,
        view: 1
    },
    {
        id: 3,
        name: "Tee T-Shirt Cotton World Hoes Brothers Step Wide Men's Presents Prestige Boats ",
        price: 301793,
        urlPic: "./images/aothunnam/3.jpg",
        urlPic2: "./images/aothunnam/3_1.jpg",
        des: "We accept Paypal where you can use all major credit cards. This item requires immediate payment.Your product will begin production immediately.If you require any adjustments to your order, please let us know right away.",
        idLoai: 1,
        new: 0,
        hot: 0,
        star: 3.5,
        sale: 0,
        view: 1
    },

    {
        id: 4,
        name: "Diaz Canel Singao, Cuba Freedom Free Cuba Democracy Vintage Men's Cotton T-Shirt ",
        price: 338000,
        urlPic: "./images/aothunnam/4.jpg",
        urlPic2: "./images/aothunnam/4_1.jpg",
        des: "Our products are 100% cotton garments and satisfaction is guaranteed.All our garments are comfortable, top quality apparel.",
        idLoai: 1,
        new: 0,
        hot: 0,
        star: 4,
        sale: 0,
        view: 1
    },
    {
        id: 5,
        name: "Nike Air Jordan 1 Mid SE GS Royal Black Toe Athletic Sneaker for Boys, Size 7 - White/Black/Light Solar Flare Heather/Hyper Royal",
        price: 3255813,
        urlPic: "./images/shoe/3.jpg",
        urlPic2: "./images/shoe/3_1.jpg",
        des: "Nike Air Jordan 1 Mid SE GS Royal Black Toe Fragment Union BQ6931-102 NEW 4Y-7Y Ships within a day! Free shipping with UPS Ground.All sales final. No returns/refunds....",
        idLoai: 2,
        new: 1,
        hot: 1,
        star: 4.5,
        sale: 1,
        view: 1
    },
    {
        id: 6,
        name: "Bear Men's It Meme Mine Cotton Eat T-Shirt It's Licked Ice I Retro Funny Tee So",
        price: 320000,
        urlPic: "./images/aothunnam/6.jpg",
        urlPic2: "./images/aothunnam/6_1.jpg",
        des: "Our products are 100% cotton garments and satisfaction is guaranteed.All our garments are comfortable, top quality apparel.",
        idLoai: 1,
        new: 0,
        hot: 0,
        star: 4,
        sale: 1,
        view: 1
    },
    {
        id: 7,
        name: "Tee Top*Gun Vintage The T Ghostrider Full Men's ",
        price: 301793,
        urlPic: "./images/aothunnam/2.jpg",
        urlPic2: "./images/aothunnam/2_1.jpg",
        des: "Classic T-shirt - sets the standard for fabric and production quality, durability and wearer comfort.100% cotton, high quality fabric and top level finishing..",
        idLoai: 1,
        new: 1,
        hot: 0,
        star: 4.5,
        sale: 1,
        view: 1
    },
    {
        id: 8,
        name: "Chicken Things I Do in My Spare Time Farmer Hobby Pie Chart Funny Men's T-Shirt",
        price: 290000,
        urlPic: "./images/aothunnam/5.jpg",
        urlPic2: "./images/aothunnam/5_1.jpg",
        des: "Our products are 100% cotton garments and satisfaction is guaranteed.All our garments are comfortable, top quality apparel.",
        idLoai: 1,
        new: 0,
        hot: 1,
        star: 4,
        sale: 1,
        view: 1
    },
    {
        id: 9,
        name: "Size 9 - Air Jordan 1 Mid 'Hyper Royal'",
        price: 3418604,
        urlPic: "./images/shoe/2.jpg",
        urlPic2: "./images/shoe/2_1.jpg",
        des: "We realize not every pair of sneakers from Nike is perfect, nor is the shoe box always perfect.In order to pass authentication, the buyer assumes all responsibility in the event there are factory flaws, defects, or imperfections when it comes to the shoes. The buyer also assumes all responsibility in the event there is damage to the shoe box, or box lid..",
        idLoai: 1,
        new: 0,
        hot: 0,
        star: 4,
        sale: 1,
        view: 1
    },



];

export default arrPro;